# Generated by Django 4.1.3 on 2022-11-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tlr_value',
            new_name='tlr',
        ),
    ]
