# Generated by Django 4.1.3 on 2022-11-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_tlr_value_event_tlr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsubject',
            name='event',
        ),
        migrations.AddField(
            model_name='eventsubject',
            name='event',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
